version: "3"
services:
  gateway:
    build: ../gateway
    ports:
      - 9527:8080
    environment:
      - TZ=Asia/Shanghai
  basedata:
    build: ../basedata
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8081:8080
  permission:
    build: ../permission
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8082:8080