version: "3"
services:

  mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - /home/suray/program/mysql/data:/var/lib/mysql
      - /home/suray/program/mysql/log:/var/log/mysql
      - /home/suray/program/mysql/conf:/etc/mysql/conf.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/suray/program/redis/data:/data
    command: redis-server --appendonly yes --requirepass "redis"

  nacos:
    image: nacos/nacos-server:1.3.2
    container_name: nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      - SPRING_DATASOURCE_PLATFORM=empty #数据源平台 仅支持mysql或不保存empty
      - MODE=standalone
    volumes:
      - /home/suray/program/nacos/logs/:/home/nacos/logs
      - /home/suray/program/nacos/plugins/:/home/nacos/plugins
    ports:
    - 8848:8848
environment:
  - TZ=Asia/Shanghai


